### ISSUE TITLE
HUD not moving to side of screen

### ISSUE THREAD

**Issue by peeves91** [LennardF1989/NiohResolution#10]
First off, thank you for the resolution patch!  It is much appreciated for 2560x1080.  Now that I'm in game with this, I find my HUD is still set for 1920x1080.  Is it easy/fixable in the .exe to move this to the actual edge of my screen?

**Comment by LennardF1989** [comment]
Unfortunately, this is not something I can easily fix. You can however try the latest version and see if it magically works now.
