### ISSUE TITLE
"patching failed" Error message.

### ISSUE THREAD

**Issue by Beklor** [LennardF1989/NiohResolution#11]
Hello
I got the following error message from the NiohResolution.exe while patching:

Please enter your desired resolution.

-> Width [default = 1920]: 3440
-> Height [default = 1080]: 1440

Please enter a scale for your desired render resolution.

Keep in mind that this scale:
- Has no effect on the entered resolution.
- Has no effect on the in-game UI.
- Can be less than 1.0 to increase performance.

-> Scale [default = 1.0]: 1.0

Unpacking nioh.exe...
-> Cannot process nioh.exe!

Unpacking of nioh.exe failed, this could mean the file is already unpacked and ready for patching.

Patching resolution to 3440x1440 with scale set to 1.0...
-> PATTERN_ASPECTRATIO1 expected 1, but got 0!

Patching failed, consider restoring a backup and try again.

Press any key to exit...

I tried it again with a new installation of Nioh but got still this message.

**Comment by LennardF1989** [comment]
On the radar, trying to get it back up to speed :) I suspect they upgraded the Steam DRM version.

**Comment by LennardF1989** [comment]
This is now fixed!

**Comment by jlhirond** [comment]
Hello, this same problem appears to be occurring again. I imagine it has to do with a DRM update again.

**Comment by LennardF1989** [comment]
Please see #12.

**Comment by composingkeys** [comment]
Hi LennardF1989,

I have Niohresolution 1.3 installed and am trying to get Nioh to run at 3440x1440 (21:9) but am running into this.

Welcome to the Nioh Resolution patcher!

Please enter your desired resolution.

-> Width [default = 1920]: 3440
-> Height [default = 1080]: 1440

Please enter a scale for your desired render resolution.

Keep in mind that this scale:
- Has no effect on the entered resolution.
- Has no effect on the in-game UI.
- Can be less than 1.0 to increase performance.

-> Scale [default = 1.0]: 1.0

Unpacking nioh.exe...
-> Cannot process nioh.exe!

Unpacking of nioh.exe failed, this could mean the file is already unpacked and ready for patching.

Patching resolution to 3440x1440 with scale set to 1.0...
-> Patching offset 8768661
-> Patching offset 21291060
-> PATTERN_MAGIC1 expected 1, but got 0!

Patching failed, consider restoring a backup and try again.

Press any key to exit...

I didn't get the game from Steam  but from Epic Games a couple of days ago. What am I doing wrong? I have Niohresoultion directly in the Nioh folder along with the original Nioh.exe file that came with the game.

**Comment by LennardF1989** [comment]
There is an active issue for this, please don't bump old closed issues :)
