### ISSUE TITLE
Fail to patch

### ISSUE THREAD

**Issue by janakptl00** [LennardF1989/NiohResolution#12]
It shows fail to patch.
DRM problem?

**Comment by LennardF1989** [comment]
I'm looking into this but I'm not seeing any updates to Nioh nor Steam DRM. Are you sure you downloaded the latest release?

**Comment by LennardF1989** [comment]
I just verified files and tried to repatch, works fine. 

Keep in mind that the FMV part of the patch is broken, which is not something I can easily fix. The actual resolution patch however, works fine. I left the FMV patch for older versions of the game, just skip it otherwise.
