### ISSUE TITLE
Hello, question regarding scaleresolution bigger then 1.0

### ISSUE THREAD

**Issue by Nichenstein** [LennardF1989/NiohResolution#13]
Thank you for this amazing mod !
Was wondering if i can upscale the game using this mod.
It seems to work but i can t tell any difference

**Comment by DFNCTSC** [comment]
@Nichenstein https://www.reddit.com/r/Nioh/comments/7cyv3m/niohresolution_v100/dpz9kqb/

> v1.1.0 is released which introduces a fix to letterboxing, as well as adding support for supersampling (or downsampling for that matter).

Supersampling = Upscaling

Yes it does, you may close this issue. (P.S. This isn't the place to post questions, this is for bugs.)

**Comment by LennardF1989** [comment]
Questions are fine, I'll close this then!
