### ISSUE TITLE
Does not work on version 1.24.1

### ISSUE THREAD

**Issue by HBbrody** [LennardF1989/NiohResolution#15]
The new game patch 1.24.1 has broken the functionality. Could you please release a version compatible with the latest Nioh release?

**Comment by Trokinos** [comment]
Confirmed, i just tested this on the epic store version that is free this week and unfortunately the current NiohResolution does not work with this new 1.24.1 patch.
Please, could you consider updating NiohResolution ?

**Comment by ScratchMode** [comment]
Lost function on the Steam version. Re-patching the exe failed too.

_Unpacking nioh.exe...
File is packed with SteamStub Variant 3.1 (x64)!
Step 1 - Read, decode and validate the SteamStub DRM header.
Step 2 - Read, decode and process the payload data.
 --> File has payload data!
Step 3 - Read, decode and dump the SteamDRMP.dll file.
 --> File has SteamDRMP.dll file!
Step 4 - Handle .bind section. Find code section.
 --> .bind section was kept in the file.
Step 5 - Read, decrypt and process code section.
 --> .text linked as main code section.
 --> .text section is encrypted.
Step 6 - Rebuild and save the unpacked file.
 --> Unpacked file saved to disk!
 --> File Saved As: nioh.exe.unpacked.exe

Patching resolution to 3440x1440 with scale set to 1.0...
-> Patching offset 8717317
-> Patching offset 19095332
-> PATTERN_MAGIC1 expected 1, but got 0!

Patching failed, consider restoring a backup and try again._

**Comment by Packuh** [comment]
Confirmed, i to tested on epic store version. current NiohResolution does not work with this new 1.24.1 patch.

**Comment by Ted-Barrett** [comment]
A temporary solution for me (I'm using epic games) is the following:
1) Set your resolution to the corresponding widescreen resolution (i.e: 2560x1440 for 3440x1440)
2) open nioh.exe with HxD and change C7 43 50 39 8E E3 3F to:
- C7 43 50 8E E3 18 40 for 3440x1440
- C7 43 50 26 B4 17 40 for 2560x1440

Basically this just changes the aspect ratio the game renders at, then in fullscreen it will be stretched to fill the whole screen. It's still techincally rendering at the lower (widescreen) resolution, but it's not super noticable, except when you try to take a screenshot it's squeezed.

Note that this only works for fullscreen mode, and the hud will be stretched. Also I haven't actually tested 2560x1080 but should work I think.

**Comment by vitzeno** [comment]
I think I've got a fix on [this pr](https://github.com/LennardF1989/NiohResolution/pull/16). 

I'm not a game dev and don't really know what I'm doing, so it would be nice for people to have a look and test it out, thanks.

**Comment by NCProduction** [comment]
@BarneyKB 
Thanks for the tip! But how do you calculate the hex value for other more exotic aspect ratio ? (for 2280x1080 as exemple)

**Comment by p1xel8ted** [comment]
The aforementioned fixes here don't appear to work as described on the Steam version. (Unpacked).

The new (Steam) EXE:
- has 0 matches for PATTERN_MAGIC1 instead of 1
- has 2 matches for PATTERN_MAGIC2 instead of 1
- has 0 matches for PATTERN_MAGIC2_B instead of 1
- has 3 matches for PATTERN_RESOLUTION instead of 2

**Comment by ScratchMode** [comment]
Was able to get this to run normally again with  Vitzeno's thread

> I think I've got a fix on [this pr](https://github.com/LennardF1989/NiohResolution/pull/16).

However I am not a programmer so not sure how to make the exe work by itself so you all can use it like before. My visual studio build exe seems to only work in the confines of the build folder , I had to drag the nioh.exe over to be modified instead of dragging the NiohResolution.exe over to the Nioh install folder for modification there. So.... un-shareable

**Comment by LennardF1989** [comment]
Working on this, will report back soon.

**Comment by ScratchMode** [comment]
This does appear to Work On **EPIC Games Launcher** version as well.
Lennard you might want to add this option to your front page description

Demonstration below.
EGS Vanilla 4k setting running on a 3440x1440 display
![Nioh Screenshot 2021 09 11 - 10 32 19 50](https://user-images.githubusercontent.com/72058050/132954921-0a5586b1-ae32-4e45-960e-584102827072.png)

Updated with the latest pull Request from Vitzeno
EGS with NiohResolution 4k setting running on a 3440X1440 display
![Nioh Screenshot 2021 09 11 - 10 35 25 16](https://user-images.githubusercontent.com/72058050/132954956-024f7b09-9921-4e65-8a6d-291ba1fed58c.png)

**Comment by LennardF1989** [comment]
Please see https://github.com/LennardF1989/NiohResolution/pull/16#issuecomment-917477562 and report findings :)
