### ISSUE TITLE
does this allow the game to be played without steam?

### ISSUE THREAD

**Issue by LV99VIVI** [LennardF1989/NiohResolution#17]
can this be used a as a crack since it uses steamless?

**Comment by LennardF1989** [comment]
Steamless does not remove the protection and you will still need to purchase the game to run it.

**Comment by ScratchMode** [comment]
For the sake of testing , I'll go ahead and install the new version from Epic Games Launcher and run it. Maybe they've left the exe completely unencrypted and it will work anyways  ¯\_(ツ)_/¯
