### ISSUE TITLE
EGS 21:9 resolution issue

### ISSUE THREAD

**Issue by kkemis** [LennardF1989/NiohResolution#22]
Patching completes successfully, but game is pillarboxed while 1920x1080 is selected in menu (although monitor OSD correctly detects 2560x1080 resolution). Pillarboxes appear up to 3840x2160 resolution, on this resolution pillarboxes no longer appear but the performance hit is extreme (not adequate to 2560x1080).
Store: Epic Games Store
Desired resolution: 2560x1080
![image](https://user-images.githubusercontent.com/94003111/142374921-d74a1c13-33b5-4aab-9b48-16d232b5f0d5.png)
![image](https://user-images.githubusercontent.com/94003111/142375000-595d2f46-0705-4a2a-918b-5edae0c82fff.png)
![ingame](https://user-images.githubusercontent.com/94003111/142375975-48c7b07d-dc19-446b-8326-2ffea2e8130a.png)

**Comment by Nexxxy** [comment]
Same for 3840x1600 / 1.0 scale @ Nioh v1.24.07

other Res than 1080p result in mini windows or too big windows / outside screen

![image](https://user-images.githubusercontent.com/6639192/148214138-ac9a413a-2451-45d4-8a67-8c3664d78b32.png)
 

Edit : Found a solution for me : All posts say that you should use Borderless. 
If I change it to 4k Fullscreen + patch it works like a charm.

**Comment by LennardF1989** [comment]
Thanks for reporting back :) Closing this as we now also have #19.
