### ISSUE TITLE
Steamdeck Compatbility

### ISSUE THREAD

**Issue by DraganHarwish1** [LennardF1989/NiohResolution#24]
Hello, 

Tried the 1.5.0 patch, the patch can be applied but the game won't run after:
First the launcher pop-up but then the game won't start (nothing happen)

Since i'm doing it on a steam deck i don't know if someone can help.

**Comment by LennardF1989** [comment]
Have you tried launching the game without the launcher?

**Comment by chinatsudori** [comment]
I also have run into this issue. Skipping the launcher yields the same results. The game launches fine without the patch, so it's only the patch making the game fail to launch with Proton

**Comment by DraganHarwish1** [comment]
Sorry for the late reply, yes i've tried without the launcher like chinatsudori, doesn't work.

**Comment by rejedai** [comment]
Same problem with proton

**Comment by rejedai** [comment]
@LennardF1989 Сan, please, share the patched exe under 3440x1440, I have an assumption that the patcher does not work properly under wine.

**Comment by rejedai** [comment]
![image](https://user-images.githubusercontent.com/92713267/199309583-b872a570-9c1d-48fc-add1-e072c701dc6b.png)
Well i was right.

![2022-11-01_21-27-44](https://user-images.githubusercontent.com/92713267/199310181-068efdce-a5df-4efa-af0c-652f513f8888.png)

Patch on native windows works well. There may be some problem in mono, the error is in the unpacked version, i.e. before applying the resolution patch.

**Comment by LennardF1989** [comment]
I don't have a Steam deck, but I would like to investigate this issue.

Could someone do the following:
- Run the patcher on the Steam deck on the latest version of the game. Remember the settings you've used.
- Run the patcher on Windows on the same version of the game using the same settings.

Send me both files, and I can do a comparison to see where the patcher might need some help on Mono. As pointed out, it may very well be related to unpacking the exe.

**Comment by rejedai** [comment]
[nioh.zip](https://github.com/LennardF1989/NiohResolution/files/9925862/nioh.zip)

**Comment by DraganHarwish1** [comment]
Thanks rejedai, i can't do it rightt now, my steam deck is in RMA.

**Comment by RyuSeisuke1992** [comment]
> [nioh.zip](https://github.com/LennardF1989/NiohResolution/files/9925862/nioh.zip)

The Linux version keeps crashing. And the Windows version starts but the image is zoomed in quite a bit. Did you work with Hex Edit?

**Comment by rejedai** [comment]
No, just the script. If there is no windows on the PC, try to generate a new exe in the virtual machine.

**Comment by LennardF1989** [comment]
This kind of slipped of my radar. Could you do it again for the latest version if it has changed @rejedai ?

**Comment by RyuSeisuke1992** [comment]
Its working on the Deck: https://www.reddit.com/r/SteamDeck/comments/11zge6q/nioh_complete_edition_remove_black_bars/

**Comment by rejedai** [comment]
> This kind of slipped of my radar. Could you do it again for the latest version if it has changed @rejedai ?

Tried, does not work. 

Patched exe via wine
[nioh.zip](https://github.com/LennardF1989/NiohResolution/files/11052157/nioh.zip)

**Comment by LennardF1989** [comment]
So, curiously, it appears Wine does something to the file header and breaks the executable. The rest of the file is exactly the same. I'll see if I can port the application to a .NET 5+ application so I can have a native Unix version.

EDIT: I would have to port the Steamless library, so gonna look into the actual issue.

**Comment by LennardF1989** [comment]
@rejedai Can you test this patcher through Wine? I tested it using WSL2 through Wine and seems to generate a proper executable that can still be run by Windows. The current version will produce broken executables through Wine.

[NiohResolution.zip](https://github.com/LennardF1989/NiohResolution/files/11070319/NiohResolution.zip)

**Comment by rejedai** [comment]
> @rejedai Can you test this patcher through Wine? I tested it using WSL2 through Wine and seems to generate a proper executable that can still be run by Windows. The current version will produce broken executables through Wine.
> 
> [NiohResolution.zip](https://github.com/LennardF1989/NiohResolution/files/11070319/NiohResolution.zip)

Very well, now it works as should through wine, thank you so much for the work and contribution to the ultrawide community!

![2023-03-26_09-52-48](https://user-images.githubusercontent.com/92713267/227760364-68e89803-09b7-4dac-9549-5951bcda5ec1.png)

**Comment by LennardF1989** [comment]
Great to hear! Have fun :)

**Comment by mutag3ne** [comment]
I put the patcher in my install's root folder, but it says that it can't find nioh.exe. Does it only look for specific directories? I have it installed on my SD card, if that makes any difference.
