### ISSUE TITLE
Security Exception

### ISSUE THREAD

**Issue by Drake713** [LennardF1989/NiohResolution#3]
![untitled](https://user-images.githubusercontent.com/30520080/33039817-8ec5e928-cdf6-11e7-97bf-8b20ba024bfb.png)

Nioh was not running, I think windows just prevented it from being modified

**Comment by LennardF1989** [comment]
Weird! I'll add some fail-safes I guess, maybe the tool itself keeps it in use.

**Comment by LennardF1989** [comment]
In retrospect, I'm pretty sure your virusscanner noticed the file changes and hijacked it for scanning. If this keeps occurring to more people, please let me know. Closed for now!
