### ISSUE TITLE
I dunno what Im doing wrong

### ISSUE THREAD

**Issue by seizamsara** [LennardF1989/NiohResolution#5]
Hi Lennard, how are u, fine? Im using the original(cracked) Nioh.exe(its a pirated version)and the process doesnt even begin. Ill send the Image of the issue and the game files here.
. I have executed both exes in admin mode and Nioh.exe is not in read only. In other order, u mention the possibility of using DSR on it; the way to use it is entering 1.1+in scale? Thnx in advance!

![sin titulo](https://user-images.githubusercontent.com/33855770/33057358-4425df9a-ce69-11e7-9971-0f98e253e34c.png)
![sin titulo2](https://user-images.githubusercontent.com/33855770/33057359-4446430c-ce69-11e7-88f4-fd651fd142b6.png)

**Comment by LennardF1989** [comment]
Verify your Steam cache, the game has been already decrypted by Steamless and cannot do it again. Also see: https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

**Comment by iadbolt** [comment]
Could you please compile a source without the unpacking stage or add a few lines to skip unpacking if the exe is already unpacked? Would fix the problem easily. Thanks.

**Comment by LennardF1989** [comment]
From the screenshots I can judge this is not a legit version of the game and I'm not willing to support that for that particular reason. Also given the group in question modified the executable, I have no guarantees the patch works anyway.

EDIT: I now see the original poster confessed this in an edit.

**Comment by iadbolt** [comment]
seizamsara, without you, I wouldnt have found the tool and the original forum thread, so Ill give the solution I found. Delete the game and reinstall it, but this time, copy everything from the codex directory except for the exe. Run Niohresolution on the original game exe and it cracks it for you xD. it will unpack the exe and then patch certain byte patterns to change the resolution.

**Comment by LennardF1989** [comment]
Steamless alone doesn't crack the game. It only removes the encryption, it will still run the SteamAPI and check if you actually own the game. I do not condone piracy in any way and am therefore going to close this issue now.
