### ISSUE TITLE
Can increase 1440x900 resolution changes?

### ISSUE THREAD

**Issue by aylz10** [LennardF1989/NiohResolution#7]
When I use 1920x1080 resolution, the game often crashes. Using the 1440x900 into the game does not crash.
Can you add a patch that modifies 1440x900 resolution? Thank you very much.

**Comment by LennardF1989** [comment]
I think it will only move the problem. If you use the patched executable without the 1920x1080 resolution set, it will still apply the other hacks (and potentially wrong aspect ratio too, btw). If that works fine as you claim, I wonder if a higher resolution might simply cause your system to go unstable?

**Comment by aylz10** [comment]
I think it is because of the win7 encoder problem led to an increase of 1080p mistakes. I will try to use the patched executable with the 1600x900 resolution set.If it crashes. It may be caused by the executable file has been modified

**Comment by aylz10** [comment]
Testing also crashed with other resolutions.It seems Steamless reasons, as long as the executable file is Steamless, it will make mistakes, regardless of the use of any resolution

**Comment by aylz10** [comment]
I found the problem with cpu, gpu, memory overclocking. When I put the cpu, gpu, memory restore the default frequency, the game does not crash now.

**Comment by LennardF1989** [comment]
Great to hear! Closing then.
