### ISSUE TITLE
Random partial black screen when fighting

### ISSUE THREAD

**Issue by greanthai420** [LennardF1989/NiohResolution#8]
Sometimes the screen turns partially black while fighting enemies and freezes, never happened before applying the patch. Have tried on 2 PCs, same problem.

Both PC uses 21:9 monitor, one 2560x1080 and another 3440x1440

**Comment by LennardF1989** [comment]
Can someone confirm this?

**Comment by LennardF1989** [comment]
Closed for inactivity.
