### ISSUE TITLE
NiohResolution download registering as Trojan

### ISSUE THREAD

**Issue by Baklavah** [LennardF1989/NiohResolution#9]
Unsure why this is happening, 2 weeks later, but it is. This is the error it's giving me:

Trojan:Win32/Fuerboos.A!cl

Do not currently have a solution, and I refuse to play with a giant black border all around my screen, or a screen that exceeds the size of my monitor... 1600x900 = 1680x1050 in full screen, and in borderless it's a box with my desktop showing all around by about 3 to 5 inches. 1920x1080 far exceeds the borders of my screen and therefore is unplayable as well. I had it set to Borderless 1824x1026 (yes, strange resolution, but I had to slightly underscan to make it fit my TV, which is my monitor).

Don't know what to do. Please help.

**Comment by LennardF1989** [comment]
Just tag it as a false positive and continue a happy gamer life. The code is here for everyone to look at, you can recompile it yourself if you don't trust my precompiled version. I can assure you it's completely safe tho.

**Comment by mendhak** [comment]
Perhaps it has to do with the  OS + AV you're using? 

On Windows 10 + built in Defender, a scan produces no threats. 

Also tried virus total, [no threats](https://www.virustotal.com/#/file/678078d3d85b6dd69dec7af3aae3c96fba5d4f8afa2d7408086f53ce092f0aa8/detection)

**Comment by LennardF1989** [comment]
How aggressive is the virusscanner for the latest version (or 1.2.0 for that matter), now that this tool is probably a bit more popular and deemed "safe"?

Closed for now tho!
